---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure System
  hosts: all
  # connection: local
  gather_facts: true
  become: true
  vars_files:
    - ./vars/vault.yml

  tasks:
    - name: Run Ping Role
      ansible.builtin.import_role:
        name: ping
      tags: ping

    - name: Run Nix Role
      ansible.builtin.import_role:
        name: nix
      tags: nix

    - name: Run Systemd Role
      ansible.builtin.import_role:
        name: systemd
      tags: systemd

    - name: Run Tailscale role
      ansible.builtin.import_role:
        name: tailscale
      tags: tailscale

    - name: Run User role
      ansible.builtin.import_role:
        name: user
      tags: user

    - name: Run Backup Role
      ansible.builtin.import_role:
        name: backup
      tags: backup

# Kubernetes deployments
# Requirements: ansible-galaxy collection install kubernetes.core
- name: Deploy Kubernetes Applications
  hosts: k3s_server
  gather_facts: false
  become: true
  vars_files:
    - ./vars/vault.yml

  tasks:
    - name: Run k8s-prereqs Role
      ansible.builtin.import_role:
        name: k8s-prereqs
      tags:
        - k8s-prereqs
        - linkding

    - name: Run Linkding Role
      ansible.builtin.import_role:
        name: linkding
      tags: linkding
