---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure System
  hosts: all
  # connection: local
  gather_facts: true
  vars_files:
    - ./vars/vault.yml

  tasks:
    - name: Run Ping Role
      ansible.builtin.import_role:
        name: ping
      tags: ping

    - name: Run Nix Role
      ansible.builtin.import_role:
        name: nix
      tags: nix

    - name: Run Systemd Role
      ansible.builtin.import_role:
        name: systemd
      tags: systemd

    - name: Run Tailscale role 
      ansible.builtin.import_role:
        name: tailscale
      tags: tailscale
 
    - name: Run User role 
      ansible.builtin.import_role:
        name: user
      tags: user

    - name: Run Backup Role
      ansible.builtin.import_role:
        name: backup
      tags: backup
