---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure System
  hosts: ubuntu-srv-01
  # connection: local
  gather_facts: true
  vars_files:
    - ./vars/vault.yml

  tasks:
    - name: Run Nix Role
      ansible.builtin.import_role:
        name: nix
      tags: nix

    - name: Run Systemd Role
      ansible.builtin.import_role:
        name: systemd
      tags: systemd

    - name: Run Tailscale role 
      ansible.builtin.import_role:
        name: tailscale
      tags: tailscale
