--- 
# Simple playbook to manage user and groups
- name: Ensure group 'users' exists
  ansible.builtin.group:
    name: "{{ default_group }}"
    state: present

- name: Ensure user 'thein3rovert' exist and is part of the 'users'
  ansible.builtin.user:
    name: "{{ default_user }}"
    groups: users
    state: present
 
