all:
  children:
    production:
      hosts:
        bellamy:
          ansible_host: 100.105.187.63
        finn:
          ansible_host: 100.81.26.84
        # trikru:
        #   ansible_host: trikru
