---
galaxy_info:
  author: Samad
  description: Deploy Longhorn distributed block storage to Kubernetes
  license: MIT
  min_ansible_version: "2.15"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - kubernetes
    - k3s
    - storage
    - longhorn
    - homelab

dependencies: []
