--- 
# Tailscale role - Install and Configure Tailscale VPN

- name: Install prerequisties
  ansible.builtin.apt:
    name:
      - curl
  become: true

- name: Check if Tailscale is installed 
  ansible.builtin.command:
    cmd: "which tailscale"
  register: tailscale_binary
  changed_when: false
  failed_when: false

  # If tailscale not installed
- name: Install Tailscale
  ansible.builtin.shell:
    cmd: "curl -fsSL https://tailscale.com/install.sh | sh"
  when: tailscale_binary.rc != 0
  become: true

- name: Enable and Start tailscaled service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: true
  become: true

- name: Check if tailscale is authenticated
  ansible.builtin.command:
    cmd: "tailscale status"
  register: tailscale_status
  changed_when: false
  failed_when: false
  become: true

# If tailscale not authenticated > authenticate
- name: Authenticate and COnfigure tailscale with auth key
  ansible.builtin.command:
    cmd: "tailscale up {{ tailscale_up_flags }} --authkey={{ tailscale_authkey }}"
  when: 
    - tailscale_status.rc != 0
    - tailscale_authkey is defined
  become: true
  no_log: true

# - name: Authenticate and COnfigure tailscale without auth key
#   ansible.builtin.command:
#     cmd: "tailscale up {{ tailscale_up_flags }}"
#   register: tailscale_login
#   ignore_errors: true
#   async: 1 
#   poll: 0
#   when: 
#     - tailscale_status.rc != 0
#     - tailscale_authkey is not defined
#   become: true

# - name: Show tailscale login
#   ansible.builtin.debug:
#     var: tailscale_login
#
- name: Capture tailscale status
  ansible.builtin.command:
    cmd: "tailscale status"
  register: final_status
  changed_when: false
  become: true

- name: Show tailscale status
  ansible.builtin.debug:
    var: final_status.stdout_lines

