---
- name: Manage tailscale service
  ansible.builtin.systemd:
    name: "{{ tailscale_service_name }}"
    state: "{{ tailscale_service_state }}"

- name: Start tailscale service
  ansible.builtin.systemd:
    name: tailsaled
    state: started

- name: Stop tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    state: stopped
  ignore_errors: yes

- name: Restart tailscale service
  ansible.builtin,systemd:
    name: tailscaled
    state: restarted
